=== PetruGurita/Liberty-Eiffel-Windows/nsis-installer/liberty/test/lib/xml/eiffeltest/data/sun/valid/dtdtest.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT root ANY>

<!ELEMENT e EMPTY>

<!ELEMENT once (e)>
<!ELEMENT twice (e,e)>

<!ENTITY % once-or-twice-a "(e,(e)?)">
<!ENTITY % once-or-twice-b "((e),e?)">
<!ENTITY % once-or-twice-c "((e),(e)?)">
<!ENTITY % once-or-twice-d "(((e)),e?)">
<!ENTITY % once-or-twice-e "(e,(((e)))?)">

<!-- disallowed by spec; a document error, parser needn't report -->
<!-- (e?,e) -->

<!ELEMENT once-or-twice-a %once-or-twice-a;>
<!ELEMENT once-or-twice-b %once-or-twice-b;>
<!ELEMENT once-or-twice-c %once-or-twice-c;>
<!ELEMENT once-or-twice-d %once-or-twice-d;>
<!ELEMENT once-or-twice-e %once-or-twice-e;>

<!-- disallowed by spec; a document error, parser needn't report -->
<!--
    <!ELEMENT once-or-twice-X (Xonce;|Xtwice)>
	... above, 'X' should be a percent sign but this comment
	is being nice to those parsers that try to parse comments
	(they shouldn't)
-->

<!ENTITY % once-or-more-a "(e+)">
<!ENTITY % once-or-more-b "(e,e*)">
<!ENTITY % once-or-more-c "((e)+)">
<!ENTITY % once-or-more-d "((e),e*)">
<!ENTITY % once-or-more-e "(e,(e)*)">

<!ELEMENT once-or-more-1a (%once-or-twice-a;,e*)>
<!ELEMENT once-or-more-1b (%once-or-twice-b;,e*)>
<!ELEMENT once-or-more-1c (%once-or-twice-c;,e*)>
<!ELEMENT once-or-more-1d (%once-or-twice-d;,e*)>
<!ELEMENT once-or-more-1e (%once-or-twice-e;,e*)>

<!ELEMENT once-or-more-2a (%once-or-twice-a;,(e)*)>
<!ELEMENT once-or-more-2b (%once-or-twice-b;,(e)*)>
<!ELEMENT once-or-more-2c (%once-or-twice-c;,(e)*)>
<!ELEMENT once-or-more-2d (%once-or-twice-d;,(e)*)>
<!ELEMENT once-or-more-2e (%once-or-twice-e;,(e)*)>

=== PetruGurita/Liberty-Eiffel-Windows/nsis-installer/liberty/test/lib/xml/eiffeltest/data/sun/valid/optional.xml
<!DOCTYPE root SYSTEM "dtdtest.dtd">
<root>
    <!--
	This primarily bangs on different ways of expressing
	optionality in content models.
    -->
    <once><e/></once>

    <twice><e/><e/></twice>


    <once-or-twice-a><e/></once-or-twice-a>
    <once-or-twice-b><e/></once-or-twice-b>
    <once-or-twice-c><e/></once-or-twice-c>
    <once-or-twice-d><e/></once-or-twice-d>
    <once-or-twice-e><e/></once-or-twice-e>

    <once-or-twice-a><e/><e/></once-or-twice-a>
    <once-or-twice-b><e/><e/></once-or-twice-b>
    <once-or-twice-c><e/><e/></once-or-twice-c>
    <once-or-twice-d><e/><e/></once-or-twice-d>
    <once-or-twice-e><e/><e/></once-or-twice-e>


    <once-or-more-1a><e/></once-or-more-1a>
    <once-or-more-1b><e/></once-or-more-1b>
    <once-or-more-1c><e/></once-or-more-1c>
    <once-or-more-1d><e/></once-or-more-1d>
    <once-or-more-1e><e/></once-or-more-1e>

    <once-or-more-1a><e/><e/></once-or-more-1a>
    <once-or-more-1b><e/><e/></once-or-more-1b>
    <once-or-more-1c><e/><e/></once-or-more-1c>
    <once-or-more-1d><e/><e/></once-or-more-1d>
    <once-or-more-1e><e/><e/></once-or-more-1e>

    <once-or-more-1a><e/><e/><e/></once-or-more-1a>
    <once-or-more-1b><e/><e/><e/></once-or-more-1b>
    <once-or-more-1c><e/><e/><e/></once-or-more-1c>
    <once-or-more-1d><e/><e/><e/></once-or-more-1d>
    <once-or-more-1e><e/><e/><e/></once-or-more-1e>

    <once-or-more-1a><e/><e/><e/><e/></once-or-more-1a>
    <once-or-more-1b><e/><e/><e/><e/></once-or-more-1b>
    <once-or-more-1c><e/><e/><e/><e/></once-or-more-1c>
    <once-or-more-1d><e/><e/><e/><e/></once-or-more-1d>
    <once-or-more-1e><e/><e/><e/><e/></once-or-more-1e>


    <once-or-more-2a><e/></once-or-more-2a>
    <once-or-more-2b><e/></once-or-more-2b>
    <once-or-more-2c><e/></once-or-more-2c>
    <once-or-more-2d><e/></once-or-more-2d>
    <once-or-more-2e><e/></once-or-more-2e>

    <once-or-more-2a><e/><e/></once-or-more-2a>
    <once-or-more-2b><e/><e/></once-or-more-2b>
    <once-or-more-2c><e/><e/></once-or-more-2c>
    <once-or-more-2d><e/><e/></once-or-more-2d>
    <once-or-more-2e><e/><e/></once-or-more-2e>

    <once-or-more-2a><e/><e/><e/></once-or-more-2a>
    <once-or-more-2b><e/><e/><e/></once-or-more-2b>
    <once-or-more-2c><e/><e/><e/></once-or-more-2c>
    <once-or-more-2d><e/><e/><e/></once-or-more-2d>
    <once-or-more-2e><e/><e/><e/></once-or-more-2e>

    <once-or-more-2a><e/><e/><e/><e/></once-or-more-2a>
    <once-or-more-2b><e/><e/><e/><e/></once-or-more-2b>
    <once-or-more-2c><e/><e/><e/><e/></once-or-more-2c>
    <once-or-more-2d><e/><e/><e/><e/></once-or-more-2d>
    <once-or-more-2e><e/><e/><e/><e/></once-or-more-2e>

</root>
